name: Node.js CI

on:
  push:
    branches: [ master, baseSprint2 ]
  pull_request:
    branches: [ master, baseSprint2  ]

jobs:
  test:

    runs-on: ubuntu-latest

    environment: config

    env:
      DB_URL: ${{ secrets.DB_URL }}
      FRONTEND: ${{ secrets.FRONTEND }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      CREDENTIALS: '{"type": "service_account", "project_id": "apicalendario-350815", "private_key_id": "3243f8f803fa74a276cd5660c469e40f2860af43", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDARkGxoy3jvsty\nxYdXOF6Vb3UiKcUu5R25tMWBcXc0tYbikT6ZD73Mbx+dFWhen69mN6QLGAEy+sQr\n/6kaedCRdFRQqtlHktkiQ0antbo+R2ymElala7VP4ZGIwaMrqJZm+kKvYh/S0qUA\noJ50YWNlmB0LCSRuu7NgZZTVDmTII2f2Q/XNpcbtr2uKM9kWYjlNubc4UuM5+fER\nfNmsJcmoPVxPo/oMf379opeVQbT1thL/fbPcEY/D56n8xhIiqo0LXOzpb3bZG76S\nKYf6lLkjgA2n8XjpughxSMSQcgI8nuFg/+SCAxJxBjvM5hMROLYpuF1BDqP+rYbm\nylSU4qsBAgMBAAECggEAA6Qc9L1GZmF/wqxUDRo4m8+21hMYjGQbN0/hnNs6Rruw\niog1uVItjeJVlNzhu2d+m8LeWtWtOaL7LapfcFx5zzRWz6mBmHfy39HKc+z2gj0J\n5R30KTkoP4NR9UcV9QLh+MCg3EeBWuWhaWjxQTrSJhuOor2tRIHOUnsv+aYmcU4G\nXOv7azIRa2KmxSXHFKL+NjkdMVgu2fxKMN9Kno/aCi2P3wtob8giprSMdM6IPrSs\nckcOATluPhwdtmWc9bAzH7HPAHdDUGcTCUkOraT3fWbmV0FkAgV6p1WuzRwMuyOs\nkgXQ+r6Yk+XiUyHeQPetY+Frlg+NZ7hOELAKHdhE8QKBgQD9encrl04a0Exyptd9\nMFL0KzMBkIF87aedBox7F22u+iDnByjp3yAjjbx/WJQVWTvcipidYa+1OS15QiQn\nn67cWyBzH0voLXMzo+Lw3Q4Ci5hIQKHupYbpRALochv7e3qqTVNihLJvOtJQ0wFU\ntRLZZkJqEqV0mdTkVDvC6o5s8QKBgQDCL+w6ZuxFBpDSy2WyifSj6Yo/G40H108O\nU7tYfMV9uX/v2lY4oecmxEnYySdd1nuz3nFjAAKWWMlPk8xs5H4U7xzI8UoV+n3E\nIvJfiMJdC6ySW3DZymWmF93vCRTw3Pt78eglg6YZCNsik6UAm6tC5XU1g/XpCWW4\nRYR2lwBfEQKBgFh1X5dH00sKPFOapAMdVSW+2asHGhlV+rOS8H2YfH+e7NKTLhUH\n9/hQY2Lxr6QPoxNhDseFqsMMtDDoAyQM1wIxjw598oiRK+3umKlEC7qZqsg0Pg7B\nl2ZahMVH5ToLKpC6MYplErw8g98O9BzyoCRcSnsoDLO3Z5NTThPEtXWRAoGAR6kZ\nuv+qZ1qh7ThkQjvIzQhtHRbUt7UMFpRtyZzZ4Kio/uGK+gE9ZUAApICvB2EUa29G\nVqt1SPhg6f337aNwp9cJv1nT5kJ3UP84hGraly2stKIMBkM7ucyK+SBX2v8hyz6d\nVeK8U/bBr4Pe21eXHuvAkkwtXp86K4Nz+7ODzpECgYEA+Lb45QWijB0P5h3iKm+g\nAtdM7eFpaLMISuh3RN3QJmyUc+K6KV8oVcmKiS2/FVZIS7r/33A9rTWFyOA+9AJT\njzbU2nCut+zyaneqylWJ6/mc71nr9VZNEdZG3vVJWS9moA/FcMtJOT82CCBCl/vU\n6BR+i+gyp5XdPbJ621OO1ic=\n-----END PRIVATE KEY-----\n", "client_email": "apicalendariogoogle@apicalendario-350815.iam.gserviceaccount.com", "client_id": "116002363257926422925", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/apicalendariogoogle%40apicalendario-350815.iam.gserviceaccount.com"}'
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
