name: Node.js CI

on:
  push:
    branches: [ master, baseSprint2 ]
  pull_request:
    branches: [ master, baseSprint2  ]

jobs:
  test:

    runs-on: ubuntu-latest

    # This is used to load Environment-level secrets, from the specified environment.
    # Instead, repository secrets are loaded by default.
    environment: production

    env:
      DB_URL: ${{ secrets.DB_URL }}
      FRONTEND: ${{ secrets.FRONTEND }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "$FRONTEND"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

